#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const source = path.join(root, 'upstream', 'pokemon-showdown-client', 'play.pokemonshowdown.com');
const output = path.resolve(process.env.PS_CLIENT_OUTPUT || path.join(root, 'dist', 'client'));
const serverHost = process.env.PS_SERVER_HOST || '127.0.0.1';
const serverPort = Number(process.env.PS_SERVER_PORT || 8000);
const registered = process.env.PS_SERVER_REGISTERED === 'true';

if (!fs.existsSync(path.join(source, 'caches', 'index-new.html'))) {
	throw new Error('Built index missing. Run `npm run build:full` first.');
}
if (!Number.isInteger(serverPort) || serverPort < 1 || serverPort > 65535) {
	throw new Error(`Invalid PS_SERVER_PORT: ${process.env.PS_SERVER_PORT}`);
}

fs.rmSync(output, {recursive: true, force: true});
fs.mkdirSync(output, {recursive: true});

const staticEntries = [
	'data', 'fx', 'js', 'sprites', 'src', 'style',
	'apple-touch-icon.png', 'favicon-16.png', 'favicon-32.png', 'favicon-256.png',
	'favicon-notify.ico', 'favicon.ico', 'manifest.json', 'pokemonshowdown.png',
	'pokemonshowdownbeta.png', 'pokemonshowdownbeta@2x.png',
];
for (const entry of staticEntries) {
	const from = path.join(source, entry);
	if (fs.existsSync(from)) fs.cpSync(from, path.join(output, entry), {recursive: true});
}

const indexHTML = fs.readFileSync(path.join(source, 'caches', 'index-new.html'), 'utf8')
	.replace('[failed to retrieve news]', '<p>暂时没有服务器公告。</p>');
fs.writeFileSync(path.join(output, 'index.html'), indexHTML);
fs.mkdirSync(path.join(output, 'config'), {recursive: true});
fs.writeFileSync(path.join(output, 'config', 'config.js'), `// Generated by scripts/package-client.mjs\nvar Config = Config || {};\nConfig.version = "zh-Hans";\nConfig.bannedHosts = [];\nConfig.whitelist = ["pokemonshowdown.com", "smogon.com"];\nConfig.routes = {\n  root: "pokemonshowdown.com",\n  client: "play.pokemonshowdown.com",\n  dex: "dex.pokemonshowdown.com",\n  replays: "replay.pokemonshowdown.com",\n  users: "pokemonshowdown.com/users",\n  teams: "teams.pokemonshowdown.com"\n};\nConfig.defaultserver = {\n  id: "showdown",\n  host: ${JSON.stringify(serverHost)},\n  port: ${serverPort},\n  registered: ${registered}\n};\n// Standalone clients store preferences locally and connect directly to defaultserver.\nConfig.testclient = true;\nConfig.roomsFirstOpenScript = function () {};\nConfig.customcolors = {};\n`);

const coverage = JSON.parse(fs.readFileSync(path.join(root, 'localization', 'generated', 'coverage.json')));
fs.writeFileSync(path.join(output, 'localization-build.json'), `${JSON.stringify({
	locale: 'zh-Hans',
	server: {host: serverHost, port: serverPort, registered},
	coverage: coverage.catalogs,
	builtAt: new Date().toISOString(),
}, null, 2)}\n`);

console.log(JSON.stringify({output, serverHost, serverPort, registered}, null, 2));
